### ISSUE TITLE
Enabling Chrome Extensions with `capabilities`

### ISSUE THREAD

**Issue by ghost** [ashbythorpe/selenium-r#3]
Hey, love the package, I'm actually using {selenider} on the surface but digging through the documentation, I believe this is more of a {selenium} question. I was actually able to figure out what I want to do, enable a Chrome extension within the client, but I'm not sure if I did it the "correct" or most elegant way. Through some research and trial and error I got to this which works:
<img width="454" alt="image" src="https://github.com/ashbythorpe/selenium-r/assets/141168652/b45a4fe5-3191-41af-b3f1-1f042f8993ac">
But I was wondering if there is a reference document for the different capabilities and the syntax to apply through. I found \`goog:chromeOptions\` in the README and the extensions part was a bit of trial and error and experience from {RSelenium}. Thanks for the great work!

**Comment by ashbythorpe** [comment]
Your method is absolutely correct, first of all.

I understand that the `capabilities` argument is quite difficult to use: I originally thought it would be used quite rarely, but am realising that this is not the case. I'd like to add helper methods (e.g. `chrome_options()`, `firefox_options()`, etc.) to mirror how other Selenium implementations manage these options. I'd also like to add some "recipes" to the selenium/selenider docs to explain some common use cases (using an extension will probably be one example).

**Comment by ghost** [comment]
Okay great, thanks for the confirmation!
